# Generated by Django 4.2.4 on 2024-09-25 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(verbose_name='Дата создания')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('price', models.CharField(max_length=50, verbose_name='Цена')),
                ('description', models.TextField(verbose_name='Описание')),
                ('icon', models.URLField(verbose_name='Иконка')),
                ('icon1', models.URLField(verbose_name='Дополнительная иконка')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_reading', models.IntegerField(blank=True, null=True, verbose_name='Последние показания')),
                ('current_reading', models.IntegerField(blank=True, null=True, verbose_name='Текущие показания')),
                ('amount_due', models.IntegerField(verbose_name='Сумма к оплате')),
                ('payment_icon', models.URLField(blank=True, null=True, verbose_name='Иконка платежа')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_screen.order', verbose_name='Заявка')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_screen.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга заявки',
                'verbose_name_plural': 'Услуги заявок',
            },
        ),
    ]
