# Generated by Django 4.2.4 on 2024-09-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_screen', '0004_alter_orderservice_current_reading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='amount_due',
            field=models.IntegerField(default=0, verbose_name='Сумма к оплате'),
        ),
    ]
