# Generated by Django 4.2.4 on 2024-09-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_screen', '0005_alter_orderservice_amount_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderservice',
            name='payment_icon',
            field=models.URLField(blank=True, default='http://127.0.0.1:9000/lab1/money_icon.svg', null=True, verbose_name='Иконка платежа'),
        ),
    ]
