# Generated by Django 4.2.4 on 2024-10-02 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_screen', '0009_order_orderservice_remove_billservice_bill_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Rent_Order',
        ),
        migrations.RenameModel(
            old_name='OrderService',
            new_name='Rent_OrderService',
        ),
        migrations.RenameModel(
            old_name='Service',
            new_name='Rent_Service',
        ),
    ]
