# Generated by Django 4.2.4 on 2024-10-02 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_screen', '0010_rename_order_rent_order_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rent_Order',
            new_name='Order',
        ),
        migrations.RenameModel(
            old_name='Rent_OrderService',
            new_name='OrderService',
        ),
        migrations.RenameModel(
            old_name='Rent_Service',
            new_name='Service',
        ),
    ]
