# Generated by Django 4.2.4 on 2024-10-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_screen', '0012_rename_order_rent_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent_order',
            name='completion_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='rent_order',
            name='formation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования'),
        ),
        migrations.AddField(
            model_name='rent_order',
            name='moderator',
            field=models.CharField(default='Moderator1', max_length=255, verbose_name='Модератор'),
        ),
    ]
