# Generated by Django 4.2.4 on 2024-10-07 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_screen', '0013_rent_order_completion_date_rent_order_formation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent_order',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AlterField(
            model_name='rent_order',
            name='formation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата формирования'),
        ),
    ]
