# Generated by Django 4.2.4 on 2024-10-07 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_screen', '0014_alter_rent_order_completion_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent_orderservice',
            name='payment_icon',
        ),
    ]
