# Generated by Django 4.2.4 on 2024-10-07 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_screen', '0015_remove_rent_orderservice_payment_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent_orderservice',
            name='amount_due',
        ),
    ]
