# Generated by Django 4.2.4 on 2024-10-14 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_screen', '0018_authuser_rent_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent_order',
            name='user',
        ),
        migrations.DeleteModel(
            name='AuthUser',
        ),
    ]
