# Generated by Django 4.2.4 on 2024-10-16 12:50

from django.db import migrations
import main_screen.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_screen', '0019_remove_rent_order_user_delete_authuser'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', main_screen.models.NewUserManager()),
            ],
        ),
    ]
