# Generated by Django 4.2.4 on 2024-10-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_screen', '0024_alter_rent_order_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent_order',
            name='client',
            field=models.IntegerField(default=1, verbose_name='Создатель'),
            preserve_default=False,
        ),
    ]
