# Generated by Django 4.2.4 on 2024-11-26 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_screen', '0026_alter_rent_order_completion_date_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rent_Service',
            new_name='Public_Service',
        ),
    ]
