# Generated by Django 4.2.4 on 2024-11-26 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_screen', '0027_rename_rent_service_public_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rent_Order',
            new_name='Addresses',
        ),
    ]
