# Generated by Django 4.2.4 on 2024-11-26 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_screen', '0028_rename_rent_order_addresses'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rent_OrderService',
            new_name='Readings',
        ),
    ]
